#!/usr/bin/env python3
import json
import os

from pygments.lexers import get_all_lexers, get_lexer_by_name

ZULIP_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../')
DATA_PATH = os.path.join(ZULIP_PATH, 'tools', 'setup', 'lang.json')
OUT_PATH = os.path.join(ZULIP_PATH, 'static', 'generated', 'pygments_data.json')
alias = {}

with open(DATA_PATH) as f:
    langs = json.load(f)

lexers = get_all_lexers()
for lexer in lexers:
    for name in lexer[1]:
        lexer_subclass_name = get_lexer_by_name(name).name
        alias[name] = lexer_subclass_name
        if name not in langs:
            langs[name] = 0

with open(OUT_PATH, 'w') as f:
    json.dump({"langs": langs, "alias": alias}, f)
