# Generated by Django 2.2.12 on 2020-06-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0282_remove_zoom_video_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='message_topic_edit_limit_seconds',
            field=models.IntegerField(default=86400),
        ),
    ]
